---
name: pipeline
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "**"
  schedule:
    - cron: 0 0 * * 0

jobs:
  pipeline:
    uses: damex-el-packages/spec-package-builder/.github/workflows/pipeline.yml@production
    with:
      gpg_key_id: A51F4C91D2EA42AB
      gpg_public_key: prometheus-2036-09-25.asc
      gpg_public_keyring: prometheus-2036-09-25.gpg
      publish: ${{ github.ref == 'refs/heads/production' }}
    secrets: inherit
